In [66]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
import math

In [67]:
df = pd.read_csv('C:\\Users\\SATORE ROHIT BALAJI\\Documents\\Machine Learning\\communication Skills.csv')
df.head()

SR NO           PRN                NAME      CA1      CA2  MID SEM Date  \
0      1  2.030000e+12      Akshay Borhade   Absent   Absent  Present  Yes   
1      2  2.030000e+12        Atharv Tavle  Present   Absent  Present  Yes   
2      3  2.030000e+12  kaushal Kshirsagar   Absent   Absent  Present   No   
3      4  2.030000e+12         Manas Patil   Absent   Absent   Absent  Yes   
4      5  2.030000e+12         Raj Mahadik   Absent  Present  Present  Yes   

   AGE  SEX  SLOPE  target  
0   12    1      0       1  
1   23    0      2       0  
2   34    0      0     122  
3   45    1      2     134  
4   22    1      2       1

In [68]:
df.describe()

SR NO           PRN        AGE       SEX     SLOPE      target
count  9.000000  9.000000e+00   9.000000  9.000000  9.000000    9.000000
mean   5.000000  2.030000e+12  27.888889  0.555556  1.111111   29.222222
std    2.738613  0.000000e+00  11.384688  0.527046  1.054093   56.084262
min    1.000000  2.030000e+12  12.000000  0.000000  0.000000    0.000000
25%    3.000000  2.030000e+12  20.000000  0.000000  0.000000    1.000000
50%    5.000000  2.030000e+12  23.000000  1.000000  2.000000    1.000000
75%    7.000000  2.030000e+12  34.000000  1.000000  2.000000    2.000000
max    9.000000  2.030000e+12  45.000000  1.000000  2.000000  134.000000

In [69]:
endog = df['target'].head(4)

In [70]:
exog =  df[['SLOPE','SEX','AGE']].head(4)

In [71]:
print(exog)

   SLOPE  SEX  AGE
0      0    1   12
1      2    0   23
2      0    0   34
3      2    1   45


In [72]:
X=exog.to_numpy()

In [73]:
Y=endog.to_numpy()

In [74]:
print(X)

[[ 0  1 12]
 [ 2  0 23]
 [ 0  0 34]
 [ 2  1 45]]


In [75]:
from numpy import array
from numpy import mean

In [76]:
from numpy import cov
from numpy.linalg import eig

In [77]:
M = mean(X.T, axis=1)

In [78]:
print(M)

[ 1.   0.5 28.5]


In [79]:
C= X-M
print(C)

[[ -1.    0.5 -16.5]
 [  1.   -0.5  -5.5]
 [ -1.   -0.5   5.5]
 [  1.    0.5  16.5]]


In [80]:
V = cov(C.T)

In [81]:
print(V)

[[  1.33333333   0.           7.33333333]
 [  0.           0.33333333   0.        ]
 [  7.33333333   0.         201.66666667]]


In [82]:
values, vectors = eig(V)

In [83]:
print(values)

[  1.06525059 201.93474941   0.33333333]


In [84]:
P = vectors.T.dot(C.T)

In [85]:
print(P.T)

[[  0.39654894  16.52551811   0.5       ]
 [ -1.20026031   5.45979626  -0.5       ]
 [  1.20026031  -5.45979626  -0.5       ]
 [ -0.39654894 -16.52551811   0.5       ]]


In [86]:
from sklearn.decomposition import PCA

In [87]:
pca = PCA(n_components=1)

In [88]:
principalComponents = pca.fit_transform(X)

In [89]:
principalDf = pd.DataFrame(data = principalComponents,columns = ['principal component 1'])

In [90]:
exog1 = sm.add_constant(principalDf[['principal component 1']])

In [91]:
print(exog1)

   const  principal component 1
0    1.0             -16.525518
1    1.0              -5.459796
2    1.0               5.459796
3    1.0              16.525518


In [92]:
from sklearn import linear_model

In [93]:
lm = linear_model.LinearRegression()

In [94]:
model = lm.fit(exog1,endog)

In [95]:
model = lm.fit(exog1,endog)

In [96]:
lm.coef_

array([0.        , 4.72758166])

In [97]:
lm.intercept_

64.25

In [98]:
def RSE(y_true, y_predicted):
    
    y_true = np.array(y_true)
    y_predicted = np.array(y_predicted)
    RSS = np.sum(np.square(y_true - y_predicted))
    rse = math.sqrt(RSS / (len(y_true) - 2))
    return rse

In [99]:
ypred =lm.predict(exog1)

In [100]:
re = RSE(endog,ypred)
print(re)

37.343057482331325
